functions.php, style.css, theme.json
Theme initialized, basic starter files added in proper hierarchy, Contributing guidelines stubbed.
=> chore: :construction: Scaffold out stubs and basic files.

README.md, example.wp-env.json
- Add the `destroy` command to the read me.
- Remove dependencies from the example `wp-env.json` file.
=> docs: 📝 Update README; remove dependencies

functions.php, parts/footer.html
Previously the short code only showed a 'last modified' date if the page had a modification. This change shows the created date if there hasn't bee a modification yet.
=> fix: 🐛 Last modified date shows created date if page is new

parts/footer-site.html, parts/footer.html, parts/header-site.html, parts/header.html
This PR adds two new site template parts that can be customized on the site level that won't interfering with future theme updates. Resolves #29
=> feat: ✨ Add customizable regions to the theme

header-plugin.php
Rework `$variables` based on new layout structure.
=> fix: :art: Adjust `header-plugin.php` to incorporate recently added `regions` classes Fixes #68

wp-blocks/rss.css
reduced font-weight to 400, bumped font-size down to "base"
=> fix: :art: RSS Feed block adjustments  Fixes #83

theme.json
This removes the lengthy custom palettes we had for several blocks and unifies the palette.
Some color variables may no longer be available in separate stylesheets.
=> fix: 🎨 Full palette is available in most blocks for text, border, and background

functions.php, wp-blocks/latest-posts.css
=> Styles: Recent Posts vs RSS Block Styles

.github/workflows/release.yml, composer.json, composer.lock, functions.php, package-lock.json, package.json
Re-include Composer and breadcrumbs constructor
=> fix: :bug: re-add Composer artifacts and breadcrumbs #71

src/scss/theme-regions/_ucsc-header.scss
Added missing bracket in `_ucsc-header.scss` that was preventing the build task.
=> fix: :bug: added missing bracket in `_ucsc-header.scss`

wp-blocks/button.css, wp-blocks/styles.js
=> feat: ✨ White, black, and blue button styles and standardized shape. Fixes #86

wp-blocks/button.css
Works relative font-size so proportions remain the same at different font-sizes. (also CSS file was linted)
=> fix: 🎨 Sets proportion of buttons to match Figma design

theme.json
Edit `theme.json` to enable link color settings #157
=> Enable users to change link color #157

parts/ucsc-footer.html
Add "Last modified:" date and style  Fixes #160
=> feat: :art: re-add "Last modified" date to `ucsc-footer.html`. Style. #160

parts/site-header.html, theme.json
=> fix(Blocks): 🎨 Reduce spacing between main navigation links  Fixes #195

.github/workflows/dokku-dev.yml, .github/workflows/pipeline-dokku.yml
Pull ucsc plugin during deployment so both theme and plugin will be available on environment
=> Add plugin checkout

.deploy/composer.json, .deploy/composer.lock, .github/workflows/dokku-dev.yml, .github/workflows/pipeline-dokku.yml, functions.php, lib/acf.php
Add options page
Add ability to hide/show universal logo
[UCSC-66](https://moderntribe.atlassian.net/browse/UCSC-66) BE: WP Admin setting to hide Universal header/footer logo
=> UCSC-66 BE: WP Admin setting to hide Universal header/footer logo

blocks/main-nav/block.json, blocks/main-nav/editor.pcss, blocks/main-nav/index.js, blocks/main-nav/index.php, blocks/main-nav/style.pcss, functions.php, index.php, lib/blocks.php, parts/site-header.html
Register new nav block for primary navigation menu
https://moderntribe.atlassian.net/browse/BM2-937
=> UCSC-98 Add Main nav block

index.php
=> UCSC-98 Remove debug

patterns/featured-image.php, patterns/featured-video.php
This PR adds two patterns to the theme. 
1. A [featured image](https://miro.com/app/board/uXjVMbYV9Fc=/?moveToWidget=3458764549633316128&cot=14) pattern
2. A [featured video](https://miro.com/app/board/uXjVMbYV9Fc=/?moveToWidget=3458764549507733827&cot=14) pattern
Patterns are uncategorized for now. We still need to decide on a categorization structure for patterns and implement it.
=> feat: 🎨 Add featured image and video patterns

parts/site-footer.html, src/scss/components/_footer-navigation.scss, src/scss/style.scss, src/scss/theme-regions/_site-footer.scss, src/scss/utilities/_mixins.scss, theme.json
- Updates the global site-footer template.
- Adds an additional column for a 3rd menu
- Added custom navigation menus to each column.
- Updated styles where applicable.
- Updated theme.json settings for nav blocks.
- [Link to ticket](https://moderntribe.atlassian.net/browse/UCSC-101)
=> Feature/ucsc 101/footer template

src/scss/components/_footer-navigation.scss
Updated some footer styles based on some design discrepancies we discovered between the 4 versions.
=> Updates styles for footer blocks.

patterns/homepage-hero.php, wp-blocks/button.css
Fixes an issue with the default href on the cta not being present.
=> Fix/ucsc 89/cta anchor

patterns/link-list.php, src/scss/block-patterns/_link-list.scss, src/scss/style.scss, src/scss/utilities/_mixins.scss
Adds a block pattern and styles for Link Lists.
Related Ticket: https://moderntribe.atlassian.net/browse/UCSC-82
=> [UCSC-82] Link List block pattern

patterns/link-list.php, patterns/statistics.php, src/scss/block-patterns/_statistics.scss
Fixes an issue with underlining on iOS browsers.
Updated the pattern to use paragraph instead of h4
Updated the link-list pattern category.
=> Fix/ucsc 87/stats block update

package-lock.json, package.json, src/js/components/main-nav.js, src/js/config/options.js, src/js/config/state.js, src/js/core/components.js, src/js/core/ready.js, src/js/core/resize.js, src/js/core/viewport-dims.js, src/js/utils/body-lock.js, src/js/utils/events.js, src/theme.js
Nav Menu updates.
- Fixes an issue with a11y where menu items were shown as aria-hidden = true on desktop
- Fixes an issue with the body scrolling when the menu is open.
- Added several util and config options for ease of use moving forward.
- Reconfigured some JS imports to clean up implementation moving forward.
=> Fix/ucsc 100/nav updates

functions.php, wp-blocks/columns.css, wp-blocks/styles.js
This is primarily for repetitive, similar content blocks to neatly display multiple items across rows using a single columns block.
- [Video explanation](https://share.cleanshot.com/lQ7DP4VKMkyL5tGNs0RY+)
=> feat: ✨ Two styles for the columns block to enable multi-row, equal-height columns

functions.php, parts/site-header.html, templates/404.html, templates/archive.html, templates/index.html, templates/page.html, templates/search.html, theme.json
Makes a few modifications to theme/template files so defaults are configured for sub-sites rather than www. 
=> July 2023 theme release modifications

src/scss/style.scss, src/scss/theme-regions/_site-content.scss, theme.json
Update block spacing in the content area and remove the space at the top of the container. Also updated the overall default spacing for blocks.
- [Link to Issue](https://moderntribe.atlassian.net/browse/UCSC-113)
- [Link to Video](https://www.loom.com/share/029b188b216f41b5b1100da2d8ad5238)
=> [UCSC-113] Content container spacing.

functions.php
Fix the skip link button a11y issues.
- [Link to Issue](https://moderntribe.atlassian.net/browse/UCSC-110)
- [Link to Video](https://www.loom.com/share/7d30a397a4ce48cba36f8f276b97ea7d)
=> [UCSC-110] - Override default skip link for a11y issues.

wp-blocks/paragraph.css
Changes intro text paragraph style from blue to black (requested by Lisa). 
=> fix: 💄 Change intro text style color to black

patterns/sidebar-with-navigation.php, src/js/block-patterns/sidebar-with-navigation.js, src/js/core/block-patterns.js, src/js/core/ready.js, src/scss/block-patterns/_sidebar-with-navigation.scss, src/scss/style.scss
Adds styles and JS behaviors for the "Content with left navigation" block pattern.
- [UCSC-134](https://example.com)](https://moderntribe.atlassian.net/browse/UCSC-134)
=> [UCSC-134] Sidebar Menu

functions.php, templates/404.html, templates/single.html
Add support for the CoAuthors Plus plugin and tidy up single and 404 template
Fixes #284 and #282
- [CoAuthors Plus support](https://github.com/ucsc/ucsc-2022/issues/284)
- [Contrast error on post dates](https://github.com/ucsc/ucsc-2022/issues/282)
=> CoAuthors Plus support and other fixes

templates/single.html
Implements the basic news article template (single.html)
- [171](https://github.com/ucsc/ucsc-2022/issues/171)
=> feat: 📝 Basic template for single posts (news articles)

.deploy/composer.json, .deploy/composer.lock, src/scss/color/_variables.scss, src/scss/style.scss, src/scss/vendors/gravity-forms.scss, src/scss/vendors/index.scss
Add gravity forms to dokku env
- https://moderntribe.atlassian.net/browse/UCSC-143
=> Add gravity forms to dokku env

patterns/sidebar-with-navigation.php, src/scss/block-patterns/_sidebar-with-navigation.scss
=> fix(pattern): Adjust spacing in and between columns in the `sidebar with navigation` pattern

parts/site-header.html
=> fix(template): Reduce the default size of the site title in the header template part

functions.php
Adds the 60th logo to global header and footer via [Truss@0.8.2](https://github.com/ucsc/truss/releases)
=> feat: Update Truss to v0.8.2
