ucsc/ucsc-2022

- functions.php
Some theme support features are enabled by default in block themes. See: https://developer.wordpress.org/themes/block-themes/block-theme-setup/#theme-support
I removed the redundant function calls from functions.php.
> Remove redundant theme support functions

- theme.json
Adding the empty arrays for `gradients` and `duotone` in the settings block of theme.json removes all of the presets from the editor. We'll leave them empty for now and consider art-directed custom presets later on.
> Reset built-in duotone and gradient presets

- functions.php
- parts/content-archive-search.html
- parts/header.html
- templates/archive.html
- templates/home.html
- templates/page.html
- templates/search.html
- templates/single.html
This PR continues the work done previously, but changes page, post, and query titles tags to use block attributes instead of filter functions in PHP.
Reference: https://developer.wordpress.org/themes/block-themes/templates-and-template-parts/#block-markup
> Site title refactoring

- theme.json
This also adds the same color options to Groups and Columns so all blocks related to layouts have the same options.
> feat: 🎨 Allow green and pink as a background color in columns block. Fixes #77

- functions.php
- wp-blocks/separator.css
- wp-blocks/styles.js
Adds small, medium, and large width sizes along side the 'wide' setting
Removes the 'default' style. Any existing separator with that setting will need to be updated.
> feat: 🎨 Add editor styles for width of separator block. Fixes #87

- functions.php
Removes PHP Notice about undeclared variable
> fix: 🐛 Do not filter page title block unless there is a breadcrumb shortcode

- functions.php
- src/scss/theme-regions/_ucsc-header.scss
- wp-blocks/search.css
I created a new `wp-blocks/search.css` file and included it via `functions.php` rather than continue in `_site-header.scss` because we'd want this removed wherever a user inserts a search block.
I no longer have access to BrowserStack, so I couldn't test this on Safari. @knice would you be able to pull this branch down and test it before merging?
> fix: :bug: Remove Safari/Webkit search form magnifying glass #132

- wp-blocks/button.css
- wp-blocks/styles.js
Deprecated button styles will revert to black until the button is updated.
> feat: 🎨 Add final button colors and style options. Resolves #86

- parts/site-header.html
- src/scss/theme-regions/_site-header.scss
- theme.json
- bump up the font scale on the two larger settings
- adjust heading block defaults to account for the scale change
- set default padding and border radius on buttons
Note: Font-sizes in existing content may need to be adjusted because the two larger font-size settings are now much larger than before.
These changes lay the groundwork for changes we will need to make when [fluid typography settings](https://make.wordpress.org/core/2022/10/03/fluid-font-sizes-in-wordpress-6-1/) become available in WordPress 6.1.
> Typography improvements

- functions.php
- parts/site-footer.html
- parts/site-header.html
- src/scss/base/_layout.scss
- src/scss/style.scss
- style.css
- templates/single.html
- theme.json
Fixes #191 
- Sets content area width to 80rem (1280px)
- Adds 'use root padding' setting to theme.json
- Adds set padding sizes for block padding settings
- Adjusts default padding on some elements
> Content area layout width increase to 1280px

- .deploy/composer.json
- functions.php
- lib/mimes.php
- parts/site-header.html
Change site-header.html template. Add 2 areas for title/logo and tagline
[UCSC-67](https://moderntribe.atlassian.net/browse/UCSC-67) BE: WP Admin setting to set logo/tagline in main header/footer
> UCSC-67 BE: WP Admin setting to set logo/tagline in main header/footer

- functions.php
- lib/blocks.php
- patterns/page-header-breadcrumbs.php
- src/scss/block-patterns/_page-header-breadcrumbs.scss
- src/scss/components/_breadbrumbs.scss
- src/scss/style.scss
- src/scss/utilities/_mixins.scss
- src/scss/utilities/_variables.scss
- templates/page-no-title-with-breadcrumbs.html
- templates/page-no-title.html
- Adds a new block pattern for a page header hero with breadcrumbs.
- Adds two new templates for a page with no title. One with breadcrumbs support and one without.
- Leveraged existing breadcrumb functions and modified them to work with the new block pattern and templates.
- Added new variables and mixins to help with content width restrictions in blocks without width support.
- Added styles for the new block pattern.
- Updated styles for breadcrumbs.
- Fixed an error with the localization domain on the blocks.php file.
- [Link to ticket](https://moderntribe.atlassian.net/browse/UCSC-84)
- [Link to the screencast](https://www.loom.com/share/941dd8579b53432ca39a677adba429b2)
> Feature/ucsc 84/breadcrumb hero

- functions.php
- lib/blocks.php
- lib/image_sizes.php
- patterns/card-grid-2-columns.php
- patterns/card-grid-3-columns.php
- patterns/card-plain-cta.php
- patterns/card-plain.php
- patterns/card-yellow.php
- src/scss/block-patterns/_cards.scss
- src/scss/style.scss
- Adds new patterns for 3 types of cards: Plain, Plain w/ CTA, and Yellow background
- Adds two new patterns for card grids. 2 column and 3 column.
- Added stylesheet partial for cards.
- Added new category for card patterns.
- Added new custom image sizes and made them available to the image block in the block editor.
Note that this is the initial pass at the cards and card grids. We can easily expand on this and add more options later. For now, these are the most common use cases presented in the designs.
- [Link to ticket](https://moderntribe.atlassian.net/browse/UCSC-94)
- [Link to ticket](https://moderntribe.atlassian.net/browse/UCSC-95)
- [Link to ticket](https://moderntribe.atlassian.net/browse/UCSC-79)
- [Link to …
> Feature/ucsc 95/card patterns

- patterns/grid-with-background-image.php
- src/scss/block-patterns/_grid-with-background-image.scss
- src/scss/style.scss
Adds the sidebar + grid/loop pattern to the theme. 
- A default pattern (the same one as the 3col w/ BG image) is applied when you first load the block.
- When replacing that image, use the repeat image option if you have a single tile for a repeatable pattern.
- The sidebar section is in its own column and the 3-column grid is its own column.
- see the screencast below for the reasoning/approach to this pattern structure.
- When adding images to they cards, use the same image ration on each card. If you mix and match them, the content will not line up properly in the text section.
- [Link to Issue](https://moderntribe.atlassian.net/browse/UCSC-86)
- [Link to Video](https://www.loom.com/share/73a3dbf4f6c343f6b28568ea444f6a22?sid=46bd537f-279a-48b …
> Feature/ucsc 86/grid with background image

- functions.php
- src/scss/components/_breadbrumbs.scss
- Set crumbs to be conditionally white or black based on page template.
- Set spacing above crumbs so the title is not smashed against the header.
- Check breadcrumbs appear when you add the page header pattern that contains breadcrumbs to a page with the 'no-title-with-breadcrumbs' template.
- Check that breadcrumbs also appear when you create a basic page one or more levels deep from the home page.
> fix: 🐛 Breadcrumbs: appearance and color

- src/scss/elements/_links.scss
- Set anchor link scroll position below fixed site header height. 
- Adds a momentary background-color to indicate the anchor target
> fix: 🐛 Set anchor link scroll position below fixed site header height

- src/js/components/main-nav.js
- src/scss/theme-regions/_site-header.scss
Adds a scroll margin based on the sticky header height so scroll targets/anchors in other regions aren't behind the sticky nav after being scrolled to.
Note that this and everything else to do with the sticky nav should be tested with a non-admin or unauthenticated session, as the WP admin bar screws with all of the height and positioning calculations.
- https://moderntribe.atlassian.net/browse/UCSC-130
> [UCSC-130] Prevent sticky header from covering scroll targets

- src/scss/theme-regions/_site-content.scss
- templates/search.html
Adds Google site search to the search results page template, and removes default padding from the search results area. 
- [Issues #40](https://github.com/ucsc/ucsc-2022/issues/40)
Links to deployed, scaffolded demo:
- [Example search results](https://wordpress-dev.ucsc.edu/?s=wordpress)
> feat: ✨ Make Google site search the default

- src/scss/base/_alignments.scss
- src/scss/style.scss
- wp-blocks/image.css
Fixes #257, which describes a 🐛 wherein images that are aligned left or right (floated) break out of their binding box 
- [UCSC's discussion](https://github.com/ucsc/ucsc-2022/issues/257)
- [Gutenberg discussion](https://github.com/WordPress/gutenberg/issues/37504)
Links to deployed, scaffolded demo:
N/A
Before
After
Again
> fix: :bug: Correct issue of images breaking out of content area

- functions.php
Don't show breadcrumbs on a post-title block that is set to be H2 or lower
Fixes #280
- [Post title block shows breadcrumbs in all instances](https://github.com/ucsc/ucsc-2022/issues/280)
> fix: 🐛 Don't show breadcrumbs on a post-title block that is set to be H2 or lower

- functions.php
- templates/single.html
1. The "author name" block is filtered to add guest authors when the the CoAuthors Plus plugin is turned on and guest authors are added to a post. 
2. The "single" template is updated to switch from the "author" block to the "author name" block, which is more minimal in settings.
Note: some "author name" UI settings will not work when Coauthors Plus is turned on.
Other post author blocks ("author" and "author biography") will be integrated later
- [#287](https://github.com/ucsc/ucsc-2022/issues/287)
- [#284](https://github.com/ucsc/ucsc-2022/issues/284)
- [video explanation](https://share.cleanshot.com/25dQg21b6GcG4lXbKKZ0)
> First level of integration with CoAuthors Plus plugin

- templates/single.html
- theme.json
- Removed the post-date block definition from theme.json. These can be configured in templates from now on
- Added a "dark-gray" color option so there are more options between light gray and black.
- [#282](https://github.com/ucsc/ucsc-2022/issues/282)
> fix: 🐛 Contrast error with date in query loop block  Fixes #282

- src/js/block-patterns/sidebar-with-navigation.js
When we on a current page that is within a submenu or has a submenu, open the submenu by default.
- [Link to Issue](https://moderntribe.atlassian.net/browse/UCSC-147)
- [Link to Video](https://www.loom.com/share/c10802aeea8c4ec5b0b13d14399df71f?sid=943e731f-b945-43b2-bb3d-e418f70015cd)
> set submenu to open if we're on the active page.

- functions.php
Fixes our site title modification script and ensures that site title blocks are properly tagged on all pages
- [#299](https://github.com/ucsc/ucsc-2022/issues/299)
1. On your home page, the site-title block in the site header area should be an h1 tag, no matter what you set it to be in the site editor.
2. On interior pages, the site-title block in the header should be an p tag, no matter what you set it to be in the site editor.
3. Any other instance of the site-title block you add to a page should not be affected by this. So if you add a site-title block to a page's content area, and set it to be an h4, it will remain an h4 when you view the published page.
> fix: 🐛 Properly modify both tags of the site-title block on home and interior pages. Fixes #299

- functions.php
- src/scss/elements/_code.scss
- src/scss/style.scss
- wp-blocks/code.css
Style the inline version of the `<code>` tag. Copied styles from Markdown. #173
Styles the inline `<code>` element. If this element is nested within a `<pre>` element, no styling is applied. This only applies to the inline element itself. Fixes #173 
- #173
- ![code-element](https://github.com/ucsc/ucsc-2022/assets/1000543/1cd8a4af-0888-4698-aab7-177153f68c7d)
> 💄 Style inline `<code>` element.

- functions.php
- wp-blocks/accordion.css
- wp-blocks/details.css
- wp-blocks/styles.js
Adds a style-sheet for the **Details Block** with custom options. Edit style-sheet for **Accordion Block** to only target a class, not the `<details>` element itself. See description in Issue #305 
- Fixes #305 
Details front-end closed
Details front-end open
Accordion front-end closed
Accordion front-end open
Accordion in the Block Editor
Details in the Block Editor
Details Styles
> 💄 Style Details Block separately from Accordion Block

- functions.php
The skip link was getting flagged for not being block level, and for not being the first child of the body. Both issues are resolved with this change.
- [Issue #293](https://github.com/ucsc/ucsc-2022/issues/293)
The skip link should appear inside of a div with a role of "navigation," just inside the body element.
> fix: 🔧 wrap a block level element around the skip link and prepend it to the body

- wp-blocks/list.css
- wp-blocks/styles.js
Adds one additional list style option for ordered and unordered lists in the list block. Nested lists can be assigned different list markers.
- [Issue 304](https://github.com/ucsc/ucsc-2022/issues/304)
> Add list style marker options for list block. Fixes #304

- functions.php
- wp-blocks/icon-block.css
- wp-blocks/styles.js
Fixes #292
Adds a style option to the Icon Block to remove the "grow" transition on hover when it is used as a link. 
- #292 
> Feat: 🎉 Remove the grow effect from linked Icon Block SVG images

- theme.json
Removes `page-no-title` template as an option for posts.
> fix: 📝 page-no-title template is only for pages, not posts

- src/scss/base/_normalize.scss
> fix(styles): Balanced text-wrap change from 'balanced' to ‘pretty’

- functions.php
Adds Landmark `role="region"` and `aria-label="Page last modification date"` attributes to **Last modified** text at bottom of footer. Fixes #327
- #327 
- [ x ] Yes. Build theme locally and use element inspector and accessibility panel to review. Ultimate test will be SiteImprove results.
> Fix: 🐛 Add ARIA landmark role for the `last-modified` date

- patterns/statistics-without-cover.php
- patterns/statistics.php
- src/scss/block-patterns/_statistics.scss
Updates the styles of the statistics block pattern and adds a second statistics block pattern that doesn't have a cover block in the background.
- #283
> feat(pattern): Update statistics block styles and add a plain stats block  Fixes #283

- src/scss/block-patterns/_cards.scss
- src/scss/elements/_links.scss
Adjust styles to add a zoom transition on all linked images (images wrapped in an `<a>` tag). 
This effect was included in the **UCSC Query Card** developed by Modern Tribe. This PR incorporates that behavior on every linked image. The redundant code was removed from the UCSC Query Card. 
Additionally, this code includes the "prefers-reduced-motion" media query, which allows a user to disable this effect via their OS.
- Issue #340 
https://github.com/user-attachments/assets/d0168da2-bde0-4362-9bdf-205db3554a56
> Feat: 🎉 Add zoom transition on linked image hover

- src/scss/elements/_links.scss
This adds a rule to the image zoom effect code to cover the situation where a linked image is inside a `div` tag instead of a `figure` tag. Further resolves #304
> fix: Add image hover zoom to featured image in latest posts block

- lib/blocks.php
Fixes the following notice when attempting to unregister a block that's not present:
`Notice: Function WP_Block_Patterns_Registry::unregister was called incorrectly. Pattern "core/social-links-shared-background-color" not found`
> Added check for block before unregistering.

- lib/blocks.php
Fixes #362
Note: These patterns will be in the pattern library again. They had preciously been hidden.
> fix: Enable required core patterns for compatibility with 6.7.x

- src/scss/elements/_links.scss
Images with links *in their captions* were getting style rules intended only for linked images. Fixes #373
> fix: 🐛 Remove image hover effect rules from caption links

- parts/site-title-with-affiliation.html
- src/scss/elements/_links.scss
This adds a template part called "site title with affiliation link" and coorespnding styles for the affiliation link above the site title in the site header. 
To test and use this, edit your site header to remove the default site title block. then insert the template part included with this PR. 
Be sure to compile styles before testing.
> feat: ✨ Template part and styles for the 'eyebrow' affiliation link
